name: PROD prices

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - run: npm install
      - run: DD_TOKEN=${{ secrets.DD_TOKEN_XIAOHUA_1 }} npm run prices
